export const CREATE_AUTH_LINK_START = "CREATE_AUTH_LINK_START";
export const CREATE_AUTH_LINK_SUCCESS = "CREATE_AUTH_LINK_SUCCESS";

export const GET_NEW_ACCESS_TOKEN_START = "GET_NEW_ACCESS_TOKEN_START";
export const GET_NEW_ACCESS_TOKEN_SUCCESS = "GET_NEW_ACCESS_TOKEN_SUCCESS";
